// Single source of truth for the portfolio gallery.
// `type` drives the frame: 'web' -> BrowserFrame, 'mobile' -> PhoneFrame.
// Every `src` must resolve to a real file under public/shots/ (generated by scripts/process-images.mjs).

export type Shot = {
  src: string;
  type: 'web' | 'mobile';
  alt: string;
  url?: string; // browser address-bar label (web shots only)
};

export type Platform = 'Web' | 'Android' | 'iOS' | 'IoT';

export type Project = {
  slug: string;
  title: string;
  icon?: string; // app-icon badge (never framed)
  role?: string;
  tech?: string;
  period?: string;
  url?: string; // default browser URL for this project's web shots
  year?: string; // short year span, e.g. '2021–23' (for the index)
  impact?: string; // headline outcome, e.g. '10k+ downloads'
  platforms?: Platform[]; // platform badges
  featured?: boolean; // gets a larger row in the Work index
  shots: Shot[];
  storeListing?: {
    android?: string;
    ios?: string;
  };
};

export const projects: Project[] = [
  {
    slug: 'otomotives',
    title: 'otomotives - Workshop CRM & ERP',
    role: 'Fullstack Developer',
    tech: 'Laravel · Vue · Gmaps · Firebase · Bluetooth · MySQL · PostgreSQL · Redis',
    icon: '/shots/otomotives/icon.png',
    year: '2021–23',
    impact: '10k+ downloads · 20+ workshops onboarded',
    url: "https://otomotives.com",
    platforms: ['Web'],
    shots: [
      { src: '/shots/otomotives/web-landing-1.png', type: 'web', alt: 'BengkelPro landing 1' },
      { src: '/shots/otomotives/web-landing-2.png', type: 'web', alt: 'BengkelPro landing 2' },
      { src: '/shots/otomotives/web-layanan-varian.png', type: 'web', alt: 'BengkelPro layanan list' },
      { src: '/shots/otomotives/internaldev.png', type: 'web', alt: 'BengkelPro internal dashboard' },
      { src: '/shots/otomotives/bengkelads.png', type: 'web', alt: 'BengkelPro ads management' },
    ],
  },
  {
    slug: 'bengkelpro',
    title: 'BengkelPro - Workshop ERP & CRM',
    role: 'Fullstack Developer',
    tech: 'Android · Kotlin · Gmaps · Firebase · Bluetooth',
    icon: '/shots/otomotives/icon.png',
    year: '2021–23',
    impact: '10k+ downloads · 20+ workshops onboarded',
    platforms: ['Android'],
    shots: [
      { src: '/shots/otomotives/android-2.jpg', type: 'mobile', alt: 'BengkelPro Android screen 2' },
      { src: '/shots/otomotives/android-3.jpg', type: 'mobile', alt: 'BengkelPro Android screen 3' },
      { src: '/shots/otomotives/android-4.jpg', type: 'mobile', alt: 'BengkelPro Android screen 4' },
      { src: '/shots/otomotives/android-5.jpg', type: 'mobile', alt: 'BengkelPro Android screen 5' },
      { src: '/shots/otomotives/android-6.jpg', type: 'mobile', alt: 'BengkelPro Android screen 6' },
      { src: '/shots/otomotives/android-7.jpg', type: 'mobile', alt: 'BengkelPro Android screen 7' },
    ],
    storeListing: {
      android: 'https://play.google.com/store/apps/details?id=com.otomotives.bengkelpro&hl=id',
    },
  },
  {
    slug: 'otomotives-mobile',
    title: 'otomotives - Workshop Booking',
    role: 'Fullstack Developer',
    tech: 'Flutter · Android · iOS · Gmaps · Firebase',
    icon: '/shots/otomotives/icon.png',
    year: '2021–23',
    impact: '10k+ downloads · 20+ workshops onboarded',
    platforms: ['Android', 'iOS'],
    shots: [
      { src: '/shots/otomotives/m-oto.jpg', type: 'mobile', alt: 'otomotives mobile home' },
      { src: '/shots/otomotives/otomaps.jpeg', type: 'mobile', alt: 'otomotives maps' },
      { src: '/shots/otomotives/otoprofile.jpeg', type: 'mobile', alt: 'otomotives profile' },
    ],
    storeListing: {
      android: 'https://play.google.com/store/apps/details?id=com.otomotives.myoto&hl=en',
      ios: 'https://apps.apple.com/id/app/otomotives-oto/id6445810865',
    },
  },
  {
    slug: 'tpm-system',
    title: 'TPM System - Factory Operations',
    role: 'Fullstack Developer',
    tech: 'Vue · Node · Express · PostgreSQL · Redis',
    period: 'Oct 2024 – Dec 2024',
    year: '2024',
    impact: 'Toyota internal platform',
    platforms: ['Web'],
    shots: [
      { src: '/shots/e-observation/dashboard.png', type: 'web', alt: 'E-Observation dashboard' },
      { src: '/shots/e-observation/dashboard-2.png', type: 'web', alt: 'E-Observation dashboard overview' },
      { src: '/shots/e-observation/schedule-activity.png', type: 'web', alt: 'Schedule activity view' },
      { src: '/shots/e-observation/calendar-planning.png', type: 'web', alt: 'Calendar planning view' },
      { src: '/shots/e-observation/master-data.png', type: 'web', alt: 'Master data management' },
    ],
  },
  {
    slug: 'kmk-digital',
    title: 'KMK Digital - Loan Finance',
    role: 'Fullstack Developer',
    tech: 'React · Java · SpringBoot · JPA · PostgreSQL · Redis',
    period: 'May 2024 – Oct 2024',
    year: '2024',
    impact: 'Spring Boot + React platform',
    platforms: ['Web'],
    shots: [
      { src: '/shots/danasakti/login.png', type: 'web', alt: 'Danasakti login page' },
      { src: '/shots/danasakti/dashboard.png', type: 'web', alt: 'Danasakti debitur dashboard' },
      { src: '/shots/danasakti/distribusi.png', type: 'web', alt: 'Danasakti distribution overview' },
      { src: '/shots/danasakti/view-4.png', type: 'web', alt: 'Danasakti view' },
      { src: '/shots/danasakti/view-5.png', type: 'web', alt: 'Danasakti view' },
    ],
  },
  {
    slug: 'mastermusic',
    title: 'MasterMusic - Music Aggregator',
    role: 'Fullstack Developer',
    tech: 'Laravel · JavaScript · Php · MySQL',
    year: '2024',
    impact: 'Music distribution aggregator',
    platforms: ['Web'],
    url: 'https://mastermusic.co.id/',
    shots: [
      { src: '/shots/mastermusic/landing-1.png', type: 'web', alt: 'MasterMusic landing 1' },
      { src: '/shots/mastermusic/landing-2.png', type: 'web', alt: 'MasterMusic landing 2' },
      { src: '/shots/mastermusic/landing-4.png', type: 'web', alt: 'MasterMusic landing 4' },
      { src: '/shots/mastermusic/landing-6.png', type: 'web', alt: 'MasterMusic landing 6' },
      { src: '/shots/mastermusic/screen-5.png', type: 'web', alt: 'MasterMusic screen' },
      { src: '/shots/mastermusic/aggregator.png', type: 'web', alt: 'MasterMusic aggregator dashboard' },
    ],
  },
  {
    slug: 'florist',
    title: 'Florist — FlowerAdvisor Seller',
    role: 'Mobile Developer',
    tech: 'Flutter · Android · iOS · Google Maps API · Firebase',
    period: 'Mar 2023 – Jun 2023',
    icon: '/shots/florist/icon.jpg',
    year: '2023',
    impact: 'Built from scratch · Play & App Store',
    platforms: ['Android', 'iOS'],
    shots: [
      { src: '/shots/florist/florist.jpg', type: 'mobile', alt: 'FlowerAdvisor Seller app' },
    ],
    storeListing: {
      ios: 'https://apps.apple.com/id/app/floweradvisor-partner/id6467772100',
      android: 'https://play.google.com/store/apps/details?id=com.flower.advisor.florist&hl=en',
    },
  },
  {
    slug: 'floweradvisor',
    title: 'FlowerAdvisor - E-commerce',
    role: 'Mobile Developer',
    tech: 'Flutter · Android · iOS · Firebase',
    period: 'Oct 2022 – Nov 2023',
    icon: '/shots/floweradvisor/icon.jpg',
    year: '2022–23',
    impact: 'Shipped to Play Store & App Store',
    platforms: ['Android', 'iOS'],
    shots: [
      { src: '/shots/floweradvisor/floweradvisor.jpg', type: 'mobile', alt: 'FlowerAdvisor app' },
    ],
    storeListing: {
      ios: 'https://apps.apple.com/id/app/floweradvisor-flowers-gift/id1185232807',
      android: 'https://play.google.com/store/apps/details?id=com.flower.advisor&hl=en',
    }
  },
  {
    slug: 'schpro',
    title: 'SchPro — Project Management',
    role: 'Mobile Developer',
    tech: 'Android · Kotlin · Firebase',
    year: '2022',
    impact: 'Sprint & project tracking app',
    platforms: ['Android'],
    shots: [
      { src: '/shots/schpro/login.png', type: 'mobile', alt: 'SchPro login' },
      { src: '/shots/schpro/register.png', type: 'mobile', alt: 'SchPro register' },
      { src: '/shots/schpro/dashboard.png', type: 'mobile', alt: 'SchPro dashboard' },
      { src: '/shots/schpro/add-project.png', type: 'mobile', alt: 'SchPro add project' },
      { src: '/shots/schpro/project-detail.png', type: 'mobile', alt: 'SchPro project detail' },
      { src: '/shots/schpro/detail-sprint.png', type: 'mobile', alt: 'SchPro sprint detail' },
      { src: '/shots/schpro/schpro-login.png', type: 'mobile', alt: 'SchPro login alternate' },
    ],
  },
  {
    slug: 'kuka',
    title: 'Kuka — Educational Game',
    role: 'Mobile Developer',
    tech: 'Mobile game · Syllable learning for kids',
    year: '2021',
    impact: 'Syllable learning game for kids',
    platforms: ['Android'],
    shots: [
      { src: '/shots/kuka/suku-kata.png', type: 'mobile', alt: 'Kuka syllable screen' },
      { src: '/shots/kuka/suku-kata-bergambar.png', type: 'mobile', alt: 'Kuka picture syllable screen' },
      { src: '/shots/kuka/tebak-suku-kata.png', type: 'mobile', alt: 'Kuka guess the syllable' },
      { src: '/shots/kuka/gameplay.png', type: 'mobile', alt: 'Kuka gameplay' },
      { src: '/shots/kuka/levelling.png', type: 'mobile', alt: 'Kuka level selection' },
      { src: '/shots/kuka/stage.png', type: 'mobile', alt: 'Kuka stage screen' },
      { src: '/shots/kuka/win.png', type: 'mobile', alt: 'Kuka win screen' },
      { src: '/shots/kuka/fail.png', type: 'mobile', alt: 'Kuka fail screen' },
    ],
  },
  {
    slug: 'dms',
    title: 'DMS — Appraisal System',
    role: 'Mobile & Web Developer',
    tech: 'C# · .NET · SQL Server · Android',
    year: '2020–21',
    impact: 'Banking clients · Bank DKI & CIMB Niaga',
    platforms: ['Web', 'Android'],
    shots: [
      { src: '/shots/dms/web-appraisal.jpg', type: 'web', alt: 'DMS web appraisal' },
      { src: '/shots/dms/mobile-appraisal.jpg', type: 'web', alt: 'DMS appraisal detail' },
      { src: '/shots/dms/jakspim.jpg', type: 'mobile', alt: 'DMS Jakspim mobile' },
    ],
  },
];
